# Setup
title:               Eun-Kang-Choi
tagline:             'A Jekyll theme'
description:         'I am <a href="https://github.com/eunkangchoi" target="_blank">@eunkangchoi</a>.'
url:                 https://eunkangchoi.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# Asset Settings
asset_url: /assets


# About/contact
author:
  name:              Eun Kang Choi
  url:               'https://ek12mv2.tistory.com'
  email:             ekk12mv2@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
